### ISSUE TITLE
Move "Metrics on ARGs" section to Methods?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/num_edges#15]
I don't think I'm alone in thinking that any serious mention of a  "Lebesgue measure" doesn't belong in the discussion of a Genetics paper!

**Comment by petrelharp** [comment]
Hm - well, the reason it's in Discussion was because it's not totally fleshed out. But, I think you're right, it could be better in the Methods. (And, I don't think it's a *serious* mention of Lebesgue measure? but really, we could change "Lebesgue measure" to "area (i.e., Lebesgue measure)" if it's actually helpful to say that there for the math audience.)  I think we do want this in there though because people (eg reviewers) are totally going to ask "is this a metric".
