### ISSUE TITLE
Drop "Parsimony" paragraph?

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/num_edges#16]
I don't really see what it adds here, and it's trying to cover a lot of stuff at the moment. What's the point of opening this can of worms, this late in the paper?

**Comment by petrelharp** [comment]
Well, one reason I wanted to put it in was because I just went and read those papers, so wanted to give a historical nod to them.  But a better reason is that I think what we're doing really does follow on from the previous "parsimony"-style papers (ie finding minimum number of recombinations); for instance, I wouldn't be surprised if the move we're describing here actually is discussed in, like, Simon's thesis or something. (I haven't checked carefully.)  So, I think it's short, and would like to keep it?  

But, maybe something like it would be better in the Introduction?

**Comment by jeromekelleher** [comment]
It's a good point. You could just mention this in the introduction in a sentence or two, with citations? A lot of the papers you're citing don't do parsimony at all (they're coalescent based things, really), and you're not citing a bunch of the parsimony ones.

The ARG paper tries to categorise this stuff fairly carefully in an appendix

**Comment by petrelharp** [comment]
I had a serious think about how to do this, and tried out various ways of inserting it into the Introduction, but didn't like any of them - I felt like it got in the way of the nice short intro. This stuff is also covered in the Appendix of Wong et al - true - but my feeling is that this paragraph is nice and short and builds some historical interest? @hfr1tz3 said she liked it. I've inserted some more references to Wong et al. So, my vote is to keep it (as minorly modified in #30)? And see what reviewers say? See what you think.
