### ISSUE TITLE
Log Figure 5B

### ISSUE THREAD

**Issue by hyanwong** [petrelharp/num_edges#25]
It looks to me like the y axis, and maybe the x axis, in Fig 5B could do with being on a log scale, and maybe an alpha value given to the points as there are lots overlaid

<img width="558" alt="Screenshot 2024-12-04 at 09 03 28" src="https://github.com/user-attachments/assets/18fd9444-8376-49f7-b9bc-359efb9cb011">

**Comment by hfr1tz3** [comment]
[Uploading figure-4-2.pdf…]()

This is something we have discussed. I've attached the figure if both axes are in the log scale. I think we decided to go against this because it looks like the method isn't as good as it actually is, as only 5% of all nodes add spans incorrectly. 

I have the opacity already set to 0.5, however I can make it lower.

I will post Figure 5 with just y-axis in log scale later today

**Comment by nspope** [comment]
Doesn't look like the attachment made it through here @hfr1tz3

**Comment by hfr1tz3** [comment]
[figure-4-2.pdf](https://github.com/user-attachments/files/18028108/figure-4-2.pdf)

**Comment by hyanwong** [comment]
> only 5% of all nodes add spans incorrectly.

You mean that 95% of the points are off the bottom of the log plot (at -infinity)? In that case you could add a constant (e.g. 1) or plot on a sqrt rather than log scale?

**Comment by nspope** [comment]
> You mean that 95% of the points are off the bottom of the log plot 

I think what @hfr1tz3 is that there's a strong correlation between incorrect span addedand total span added, which makes it look like all the span added is bad at first glance when this is really not the case. IMO adding a 1-to-1 line or making the x-axis "correctly added span" would clarify this

**Comment by hyanwong** [comment]
If 95% of points don't add incorrect spans, shouldn't they have a y-axis value of 0? Maybe I misunderstood the plot labels?

**Comment by hfr1tz3** [comment]
If we log the y-axis, there is no 0 y-value as it gets removed (log(0) DNE) which is why are plots look misleading. 

Thanks for all the comments. I will just post a bunch of options, and we can choose what looks best. 

The first is the original added span vs incorrectly added span with a 1-1 line and we log the y-axis.
![Log-y-plot](https://github.com/user-attachments/assets/f39b9417-2fd5-4e2b-84a0-ab49520f50e4)

added span vs incorrectly added span with 1-1 line and log scale on both axes
![log-x-y-added-v-wrong](https://github.com/user-attachments/assets/e9f0e88f-f549-47bd-8479-4a05316744fa)

added span vs incorrectly added span with 1-1 line with log scale on x-axis. 
![log-x-added-v-wrong](https://github.com/user-attachments/assets/a99fccd9-5cc2-44a3-abe1-56cb38c5451c)

With the next plots, this point is actually already covering in our supplemental histogram. Less than 1000 nodes have a nonzero proportion of incorrectly added span, but this is what the correctly added span vs incorrect proportion graphs look like.

added correct vs incorrect proportion with log on the xaxis.
![correct-v-propincorrect-log](https://github.com/user-attachments/assets/dded711e-0aee-490b-8627-559c39a716c6)

added correct vs incorrect proportion with usual scaling
![correct-v-propincorrect](https://github.com/user-attachments/assets/643b9c61-6c88-4404-ac2d-e077f6a98bbb)

Alternatively, we could have the top row of Figure 5 be two histograms. A being the same and then B is the proportion incorrect span, see here 
![newplot (14)](https://github.com/user-attachments/assets/c4ce7234-d794-4227-9750-7076694d96ec)

then we can provide one of the added span - vs incorrectly added span plots as a supplement. This option might make the most sense actually, but I would love to know what y'all think.

**Comment by hyanwong** [comment]
> If we log the y-axis, there is no 0 y-value as it gets removed (log(0) DNE) which is why are plots look misleading.

So why don't you just add a constant before logging (this is pretty conventional)?

**Comment by hfr1tz3** [comment]
> So why don't you just add a constant before logging (this is pretty conventional)?

I should do that. I don't know that option didn't cross my mind. It looks much better now. 

![image](https://github.com/user-attachments/assets/3f33f6b4-52c4-4ba0-864e-32c536ae8919)

**Comment by hyanwong** [comment]
Great. You can probably adjust the first label on the y-axis so that it reads '0' if you really want to, but perhaps that would confuse people.

**Comment by hfr1tz3** [comment]
I think I will just keep it as is.

**Comment by petrelharp** [comment]
We also wanted it to be `0` not `1`, fyi.
